import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProviderCustom } from "../themes/ThemeContext"; // Asegúrate de que la ruta sea correcta
// import ThemeToggle from "./ThemeToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <ThemeProviderCustom>
          {/* <ThemeToggle /> */}
          {children}
        </ThemeProviderCustom>
      </body>
    </html>
  );
}
